### ISSUE TITLE
计算解密文字corpid不匹配或校验失败的问题

### ISSUE THREAD

**Issue by zjun615** [elixirChain/dingtalk-encrypt#10]
按照文档的示例解密
```
const encryptor = new DingTalkEncryptor(token, aes_key, corpId);
// 解密
encryptor.getDecryptMsg(params.signature, params.timestamp, params.nonce, encrypt);
```

结果报错：
`
{"msgMap":{},"code":900010,"message":"计算解密文字corpid不匹配"}
`
开放平台报校验失败

经过反复对比其它语言的解密方法和开发文档，发现`DingTalkEncryptor(token, aes_key, corpId)`中的第3个参数`corpId`并**非**_corpId_，而是**appKey**

**Comment by Leocat81** [comment]
> 按照文档的示例解密
> 
> ```
> const encryptor = new DingTalkEncryptor(token, aes_key, corpId);
> // 解密
> encryptor.getDecryptMsg(params.signature, params.timestamp, params.nonce, encrypt);
> ```
> 
> 结果报错： `{"msgMap":{},"code":900010,"message":"计算解密文字corpid不匹配"}` 开放平台报校验失败
> 
> 经过反复对比其它语言的解密方法和开发文档，发现`DingTalkEncryptor(token, aes_key, corpId)`中的第3个参数`corpId`并**非**_corpId_，而是**appKey**

确实，这个好坑呀，希望官方订正修复一下。

**Comment by 17Damon** [comment]
文档中的参数 CORP_ID 具有歧义，后面会更改为KEY。
并且说明以下内容。

> 第三方企业应用：$key填写对应的suiteKey。
> 
> 企业定制应用：$key填写对应的customKey。
> 
> 企业内部应用：$key填写企业的Corpid。

官方文档：

[加解密方案说明](https://open.dingtalk.com/document/orgapp/callback-event-message-body-encryption-and-decryption#title-082-lby-s08)

**Comment by 17Damon** [comment]
文档中的参数 CORP_ID 具有歧义，后面会更改为KEY。
并且说明以下内容。

> 第三方企业应用：$key填写对应的suiteKey。
> 
> 企业定制应用：$key填写对应的customKey。
> 
> 企业内部应用：$key填写企业的Corpid。

详见官方文档：

[加解密方案说明](https://open.dingtalk.com/document/orgapp/callback-event-message-body-encryption-and-decryption#title-082-lby-s08)
