### ISSUE TITLE
传参是应用的Client ID (原 AppKey 和 SuiteKey)，不是corpId，大家小心。。。巨坑

### ISSUE THREAD

**Issue by seasolzombie** [elixirChain/dingtalk-encrypt#11]
new DingTalkEncryptor(token, aes_key, clientId)
DingTalkEncryptor 第三个参数是应用的Client ID (原 AppKey 和 SuiteKey)

**Comment by 17Damon** [comment]
详见 https://github.com/elixirChain/dingtalk-encrypt/issues/10
