### ISSUE TITLE
含有中文内容时，解码出来为乱码，测试文件EncryptTest.js的例子也是乱码

### ISSUE THREAD

**Issue by caiyangwei** [elixirChain/dingtalk-encrypt#2]
![image](https://user-images.githubusercontent.com/30101744/122347868-17144c80-cf7d-11eb-8eda-3ba0e1fa377a.png)

**Comment by yu3wen** [comment]
解决了吗？我也遇到了这个问题

**Comment by senique** [comment]
使用 v2.0.0 试试

**Comment by senique** [comment]
> 使用 v2.0.0 试试


最新版 v2.0.1 已经发布
