### ISSUE TITLE
2.0.1 getRandomStr() TypeError: Assignment to constant variable

### ISSUE THREAD

**Issue by JoveYao** [elixirChain/dingtalk-encrypt#6]
getRandomStr() TypeError: Assignment to constant variable.
看了下修改， 2.0.0 是 let 定义的变量，2.0.1 换 const 出错了。

**Comment by senique** [comment]
> getRandomStr() TypeError: Assignment to constant variable. 看了下修改， 2.0.0 是 let 定义的变量，2.0.1 换 const 出错了。

已经修复。试用 2.1.0
应该是在 TS 环境会报错，直接测试没有发现。

**Comment by senique** [comment]
> getRandomStr() TypeError: Assignment to constant variable. 看了下修改， 2.0.0 是 let 定义的变量，2.0.1 换 const 出错了。

已经修复，试用 2.1.0。
应该是在 TS 环境会报错，直接测试没有报错。
