### ISSUE TITLE
看数据已经解析出来了，可就是不对

### ISSUE THREAD

**Issue by lishy97** [elixirChain/dingtalk-encrypt#8]
![image](https://user-images.githubusercontent.com/68091271/207318642-4fa0fd4b-345b-46c2-ac38-3aa014af8dc6.png)

**Comment by ChrisDoufu** [comment]
我也遇上了一样的问题，请问咋解决的？

**Comment by 17Damon** [comment]
详见 https://github.com/elixirChain/dingtalk-encrypt/issues/10

**Comment by 17Damon** [comment]
详见 https://github.com/elixirChain/dingtalk-encrypt/issues/10
