### ISSUE TITLE
使用Crypt-js这个包的话，建议参考1.2.1那个的解密，贼好用。

### ISSUE THREAD

**Issue by SinMu-L** [elixirChain/dingtalk-encrypt#9]
看到这个我就感觉会了

![image](https://user-images.githubusercontent.com/39164106/211969836-296f11d0-916b-4e66-bd0c-d88745ca8d48.png)
![image](https://user-images.githubusercontent.com/39164106/211969870-4a8dd2bc-06ed-4be1-93a9-95ce56ba27df.png)

**Comment by 17Damon** [comment]
请等待文档更新。
